### ISSUE TITLE
Arch x86_64 is not supported

### ISSUE THREAD

**Issue by dannydorfel** [justicel/puppet-wkhtmltox#3]
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: validate_re(): "x86_64" does not match "^i386$|^amd64$" at init.pp

I first thought it would be be solved by using: 
validate_re($arch, '^i386$|^amd64$|^x86_64$')

But then it's not downloading the required package ofcourse. There should be a nice check in params.pp to set the $arch variable to amd64 if $::architecture == "x88_64"

case $::architecture {
    'x86_64': {
        $arch = 'amd64'
    }
    default: {
        $arch = $::architecture
    }
}

**Comment by justicel** [comment]
Resolved in latest release. Thanks fore reporting.
