### ISSUE TITLE
Dependency of package xorg-x11-fonts-75dpi missing

### ISSUE THREAD

**Issue by dannydorfel** [justicel/puppet-wkhtmltox#4]
CentOS 6.5

Error: Execution of '/bin/rpm -i /tmp/wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm' returned 1: error: Failed dependencies:
	xorg-x11-fonts-75dpi is needed by wkhtmltox-1:0.12.2.1-1.x86_64

Sould be added to the $required_pkgs in params.pp

**Comment by justicel** [comment]
Fixed in latest revision. Thanks.
